package projetocg;

import java.awt.Color;
import java.awt.Graphics;
import projetocg.Bresenham;
import java.util.ArrayList;
import java.util.Arrays; 

public class InterfacePrincipal extends javax.swing.JFrame {
    public int HEIGHT = 640;
    public int WIDTH  =  640;
    public int TAMPIXEL = 20;
    public boolean controle_grid = false;
    int qtde_pixels = (WIDTH - TAMPIXEL)/TAMPIXEL;
    int xInicial = 0, yInicial = 0, xFinal = 0, yFinal = 0;
    ArrayList<Pontos> arestas_poligono = new ArrayList<>(); //P1 e P2 das arestas
    ArrayList<Pontos> pontos_poligono = new ArrayList<>(); //Todos os pontos
    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFrameBuffer = new javax.swing.JPanel();
        xInicialLinha = new javax.swing.JTextField();
        yInicialLinha = new javax.swing.JTextField();
        labelPontoInicialLinha = new javax.swing.JLabel();
        labelPontoFinalLinha = new javax.swing.JLabel();
        xFinalLinha = new javax.swing.JTextField();
        yFinalLinha = new javax.swing.JTextField();
        labelXInicialLinha = new javax.swing.JLabel();
        labelXFinalLinha = new javax.swing.JLabel();
        labelYInicialLinha = new javax.swing.JLabel();
        labelYFinalLinha = new javax.swing.JLabel();
        botaoLinha = new javax.swing.JButton();
        labelBotaoGrid = new javax.swing.JLabel();
        botaoGrid = new javax.swing.JToggleButton();
        labelCentro = new javax.swing.JLabel();
        xCentro = new javax.swing.JTextField();
        labelXCentro = new javax.swing.JLabel();
        labelYCentro = new javax.swing.JLabel();
        yCentro = new javax.swing.JTextField();
        labelRaio = new javax.swing.JLabel();
        raio = new javax.swing.JTextField();
        labelRaioR = new javax.swing.JLabel();
        botaoCirculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoPreenchimentoRecursivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelXMin = new javax.swing.JLabel();
        labelYMin = new javax.swing.JLabel();
        xMin = new javax.swing.JTextField();
        yMin = new javax.swing.JTextField();
        labelXMax = new javax.swing.JLabel();
        labelYMax = new javax.swing.JLabel();
        xMax = new javax.swing.JTextField();
        yMax = new javax.swing.JTextField();
        botaoCriarJanela = new javax.swing.JButton();
        botaoPoligono = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botaoPreenchimentoVarredura = new javax.swing.JButton();
        botaoRecortePoligono = new javax.swing.JButton();
        botaoRecorteLinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 680));

        painelFrameBuffer.setBackground(new java.awt.Color(255, 255, 255));
        painelFrameBuffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelFrameBuffer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelFrameBuffer.setMaximumSize(new java.awt.Dimension(640, 460));
        painelFrameBuffer.setMinimumSize(new java.awt.Dimension(640, 460));
        painelFrameBuffer.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout painelFrameBufferLayout = new javax.swing.GroupLayout(painelFrameBuffer);
        painelFrameBuffer.setLayout(painelFrameBufferLayout);
        painelFrameBufferLayout.setHorizontalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        painelFrameBufferLayout.setVerticalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        xInicialLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xInicialLinhaActionPerformed(evt);
            }
        });

        yInicialLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yInicialLinhaActionPerformed(evt);
            }
        });

        labelPontoInicialLinha.setText("Ponto inicial");

        labelPontoFinalLinha.setText("Ponto final");

        xFinalLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFinalLinhaActionPerformed(evt);
            }
        });

        yFinalLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yFinalLinhaActionPerformed(evt);
            }
        });

        labelXInicialLinha.setText("X");

        labelXFinalLinha.setText("X");

        labelYInicialLinha.setText("Y");

        labelYFinalLinha.setText("Y");

        botaoLinha.setText("Desenhar linha");
        botaoLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLinhaActionPerformed(evt);
            }
        });

        labelBotaoGrid.setText("Grid");

        botaoGrid.setText("Desligado");
        botaoGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGridActionPerformed(evt);
            }
        });

        labelCentro.setText("Centro");

        xCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCentroActionPerformed(evt);
            }
        });

        labelXCentro.setText("X");

        labelYCentro.setText("Y");

        yCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yCentroActionPerformed(evt);
            }
        });

        labelRaio.setText("Raio");

        raio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raioActionPerformed(evt);
            }
        });

        labelRaioR.setText("r");

        botaoCirculo.setText("Desenhar círculo");
        botaoCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCirculoActionPerformed(evt);
            }
        });

        jLabel1.setText("   0    1    2    3    4    5    6    7    8    9    10   11  12  13  14  15 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31");

        botaoPreenchimentoRecursivo.setText("Preenc.Rec.");
        botaoPreenchimentoRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPreenchimentoRecursivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Janela de recorte");

        labelXMin.setText("xmin");

        labelYMin.setText("ymin");

        labelXMax.setText("xmax");

        labelYMax.setText("ymax");

        botaoCriarJanela.setText("Criar janela");
        botaoCriarJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarJanelaActionPerformed(evt);
            }
        });

        botaoPoligono.setText("Desenhar polígono");
        botaoPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPoligonoActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir pontos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoPreenchimentoVarredura.setText("Preenc.Varred.");

        botaoRecortePoligono.setText("Recorte polig.");
        botaoRecortePoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecortePoligonoActionPerformed(evt);
            }
        });

        botaoRecorteLinha.setText("Recorte linha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelXCentro)
                                    .addComponent(labelRaioR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCentro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelYCentro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelRaio)
                                    .addComponent(raio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelXMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xMin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelXMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xMax, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelYMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoCriarJanela)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yMin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelYMax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yMax, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBotaoGrid)
                                    .addComponent(botaoGrid)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelXInicialLinha)
                                            .addComponent(labelXFinalLinha, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(xFinalLinha)
                                                    .addComponent(xInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelYInicialLinha)
                                                    .addComponent(labelYFinalLinha))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(yInicialLinha)
                                                    .addComponent(yFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(labelPontoInicialLinha)
                                            .addComponent(labelPontoFinalLinha)
                                            .addComponent(botaoLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(botaoPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoRecorteLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoPreenchimentoVarredura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoPreenchimentoRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoRecortePoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPontoInicialLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXInicialLinha)
                            .addComponent(labelYInicialLinha)
                            .addComponent(botaoPreenchimentoRecursivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPontoFinalLinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(xFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelXFinalLinha)
                                    .addComponent(labelYFinalLinha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoLinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPoligono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoPreenchimentoVarredura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRecortePoligono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRecorteLinha)))
                        .addGap(18, 18, 18)
                        .addComponent(labelCentro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXCentro)
                            .addComponent(labelYCentro)
                            .addComponent(yCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRaio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRaioR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCirculo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelXMin)
                            .addComponent(xMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXMax)
                            .addComponent(xMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelYMin)
                            .addComponent(yMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelYMax)
                            .addComponent(yMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCriarJanela)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBotaoGrid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoGrid))
                    .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yInicialLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yInicialLinhaActionPerformed
        
    }//GEN-LAST:event_yInicialLinhaActionPerformed

    private void yFinalLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yFinalLinhaActionPerformed
        
    }//GEN-LAST:event_yFinalLinhaActionPerformed
    
    private void botaoLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLinhaActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        Bresenham bresenham = new Bresenham();
        
        xInicial = Integer.parseInt(xInicialLinha.getText());
        yInicial = Integer.parseInt(yInicialLinha.getText());
        xFinal = Integer.parseInt(xFinalLinha.getText());
        yFinal = Integer.parseInt(yFinalLinha.getText());
        
        bresenham.iniciar_breserham(xInicial, xFinal, yInicial, yFinal, TAMPIXEL, qtde_pixels, g);
    }//GEN-LAST:event_botaoLinhaActionPerformed

    private void xInicialLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xInicialLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xInicialLinhaActionPerformed

    private void xFinalLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFinalLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xFinalLinhaActionPerformed

    private void botaoGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGridActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
  
        if(controle_grid == false){
            controle_grid = true;
            botaoGrid.setText("Ligado");
            for(int j=0; j<painelFrameBuffer.getHeight(); j=j+TAMPIXEL){
                for(int i=0; i<painelFrameBuffer.getWidth(); i=i+TAMPIXEL){
                    g.drawRect(i, j, TAMPIXEL, TAMPIXEL);
                }
            }   
        }else{
            controle_grid = false;
            botaoGrid.setText("Desligado");
            painelFrameBuffer.repaint();
            arestas_poligono = new ArrayList<>(); //P1 e P2 das arestas
            pontos_poligono = new ArrayList<>(); //Todos os pontos
        }
    }//GEN-LAST:event_botaoGridActionPerformed

    private void xCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xCentroActionPerformed

    private void yCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yCentroActionPerformed

    private void raioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raioActionPerformed

    private void botaoCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCirculoActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        PontoMedio pontoMedio = new PontoMedio();
        int xCentral = Integer.parseInt(xCentro.getText());
        int yCentral = Integer.parseInt(yCentro.getText());
        int raioCirculo = Integer.parseInt(raio.getText());
        
        pontoMedio.desenharCirculo(xCentral, yCentral, raioCirculo, TAMPIXEL, qtde_pixels, g);
    }//GEN-LAST:event_botaoCirculoActionPerformed

    private void botaoPreenchimentoRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPreenchimentoRecursivoActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        Preenchimento preenchimento = new Preenchimento();
        
        preenchimento.preenchimento(pontos_poligono, "recursivo", TAMPIXEL, qtde_pixels, g);
    }//GEN-LAST:event_botaoPreenchimentoRecursivoActionPerformed

    private void botaoCriarJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarJanelaActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        ArrayList<Pontos> pontos = new ArrayList<>();
        Bresenham bresenham = new Bresenham();
        
        g.setColor(Color.yellow);
        
        xInicial = Integer.parseInt(xInicialLinha.getText());
        yInicial = Integer.parseInt(yInicialLinha.getText());
        xFinal = Integer.parseInt(xFinalLinha.getText());
        yFinal = Integer.parseInt(yFinalLinha.getText());
        int xmin = Integer.parseInt(xMin.getText());
        int xmax = Integer.parseInt(xMax.getText());
        int ymin = Integer.parseInt(yMin.getText());
        int ymax = Integer.parseInt(yMax.getText());
        
        pontos.add(new Pontos(xInicial, yInicial));
        pontos.add(new Pontos(xFinal, yFinal));
        
        //Criação da janela de recorte
        for(int x = xmin; x <= xmax; x++){
            for(int y = ymin; y <= ymax; y++){
                g.fillRect(x*TAMPIXEL, Math.abs((y-qtde_pixels)*TAMPIXEL), TAMPIXEL, TAMPIXEL);
            }
        }
        
        bresenham.iniciar_breserham_recorte(pontos.get(0), pontos.get(1), TAMPIXEL, qtde_pixels, g, xmin, xmax, ymin, ymax);
    }//GEN-LAST:event_botaoCriarJanelaActionPerformed

    private void botaoPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPoligonoActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        Bresenham bresenham = new Bresenham();
        ArrayList<Pontos> pontos_aresta = new ArrayList<>();
        
        xInicial = Integer.parseInt(xInicialLinha.getText());
        yInicial = Integer.parseInt(yInicialLinha.getText());
        xFinal = Integer.parseInt(xFinalLinha.getText());
        yFinal = Integer.parseInt(yFinalLinha.getText());
        
        pontos_aresta = bresenham.iniciar_breserham(xInicial, xFinal, yInicial, yFinal, TAMPIXEL, qtde_pixels, g);
        
        //Adiciona P1 e P2 de uma aresta do poligono em um array
        arestas_poligono.add(new Pontos(xInicial, yInicial));
        arestas_poligono.add(new Pontos(xFinal, yFinal));
        
        //Adiciona todos os pontos em um array
        for(int i = 0; i<pontos_aresta.size(); i++){
            pontos_poligono.add(new Pontos(pontos_aresta.get(i).x, pontos_aresta.get(i).y));
        }
    }//GEN-LAST:event_botaoPoligonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("LISTA DE ARESTAS\n");
        for(int i = 0; i < arestas_poligono.size(); i++){
            System.out.println("x: "+arestas_poligono.get(i).x+", y: "+arestas_poligono.get(i).y);
        }
        
        System.out.println("LISTA DE TODOS OS PONTOS\n");
        for(int i = 0; i < pontos_poligono.size(); i++){
            System.out.println("x: "+pontos_poligono.get(i).x+", y: "+pontos_poligono.get(i).y);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoRecortePoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecortePoligonoActionPerformed
        
    }//GEN-LAST:event_botaoRecortePoligonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCirculo;
    private javax.swing.JButton botaoCriarJanela;
    private javax.swing.JToggleButton botaoGrid;
    private javax.swing.JButton botaoLinha;
    private javax.swing.JButton botaoPoligono;
    private javax.swing.JButton botaoPreenchimentoRecursivo;
    private javax.swing.JButton botaoPreenchimentoVarredura;
    private javax.swing.JButton botaoRecorteLinha;
    private javax.swing.JButton botaoRecortePoligono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBotaoGrid;
    private javax.swing.JLabel labelCentro;
    private javax.swing.JLabel labelPontoFinalLinha;
    private javax.swing.JLabel labelPontoInicialLinha;
    private javax.swing.JLabel labelRaio;
    private javax.swing.JLabel labelRaioR;
    private javax.swing.JLabel labelXCentro;
    private javax.swing.JLabel labelXFinalLinha;
    private javax.swing.JLabel labelXInicialLinha;
    private javax.swing.JLabel labelXMax;
    private javax.swing.JLabel labelXMin;
    private javax.swing.JLabel labelYCentro;
    private javax.swing.JLabel labelYFinalLinha;
    private javax.swing.JLabel labelYInicialLinha;
    private javax.swing.JLabel labelYMax;
    private javax.swing.JLabel labelYMin;
    private javax.swing.JPanel painelFrameBuffer;
    private javax.swing.JTextField raio;
    private javax.swing.JTextField xCentro;
    private javax.swing.JTextField xFinalLinha;
    private javax.swing.JTextField xInicialLinha;
    private javax.swing.JTextField xMax;
    private javax.swing.JTextField xMin;
    private javax.swing.JTextField yCentro;
    private javax.swing.JTextField yFinalLinha;
    private javax.swing.JTextField yInicialLinha;
    private javax.swing.JTextField yMax;
    private javax.swing.JTextField yMin;
    // End of variables declaration//GEN-END:variables
  
public void construirGrade(){
    Graphics g = painelFrameBuffer.getGraphics();
    
    g.drawLine(0, 0, 200, 150);
}

}
