package projetocg;

import java.awt.Color;
import java.awt.Graphics;
import projetocg.Bresenham;
import java.util.ArrayList;
import java.util.Arrays; 

public class InterfacePrincipal extends javax.swing.JFrame {
    public int HEIGHT = 640;
    public int WIDTH  =  640;
    public int TAMPIXEL = 20;
    public boolean controle_grid = false;
    int qtde_pixels = (WIDTH - TAMPIXEL)/TAMPIXEL;
    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFrameBuffer = new javax.swing.JPanel();
        xInicialLinha = new javax.swing.JTextField();
        yInicialLinha = new javax.swing.JTextField();
        labelPontoInicialLinha = new javax.swing.JLabel();
        labelPontoFinalLinha = new javax.swing.JLabel();
        xFinalLinha = new javax.swing.JTextField();
        yFinalLinha = new javax.swing.JTextField();
        labelXInicialLinha = new javax.swing.JLabel();
        labelXFinalLinha = new javax.swing.JLabel();
        labelYInicialLinha = new javax.swing.JLabel();
        labelYFinalLinha = new javax.swing.JLabel();
        botaoLinha = new javax.swing.JButton();
        labelBotaoGrid = new javax.swing.JLabel();
        botaoGrid = new javax.swing.JToggleButton();
        labelCentro = new javax.swing.JLabel();
        xCentro = new javax.swing.JTextField();
        labelXCentro = new javax.swing.JLabel();
        labelYCentro = new javax.swing.JLabel();
        yCentro = new javax.swing.JTextField();
        labelRaio = new javax.swing.JLabel();
        raio = new javax.swing.JTextField();
        labelRaioR = new javax.swing.JLabel();
        botaoCirculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 680));

        painelFrameBuffer.setBackground(new java.awt.Color(255, 255, 255));
        painelFrameBuffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelFrameBuffer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelFrameBuffer.setMaximumSize(new java.awt.Dimension(640, 460));
        painelFrameBuffer.setMinimumSize(new java.awt.Dimension(640, 460));
        painelFrameBuffer.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout painelFrameBufferLayout = new javax.swing.GroupLayout(painelFrameBuffer);
        painelFrameBuffer.setLayout(painelFrameBufferLayout);
        painelFrameBufferLayout.setHorizontalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        painelFrameBufferLayout.setVerticalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        xInicialLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xInicialLinhaActionPerformed(evt);
            }
        });

        yInicialLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yInicialLinhaActionPerformed(evt);
            }
        });

        labelPontoInicialLinha.setText("Ponto inicial");

        labelPontoFinalLinha.setText("Ponto final");

        xFinalLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFinalLinhaActionPerformed(evt);
            }
        });

        yFinalLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yFinalLinhaActionPerformed(evt);
            }
        });

        labelXInicialLinha.setText("X");

        labelXFinalLinha.setText("X");

        labelYInicialLinha.setText("Y");

        labelYFinalLinha.setText("Y");

        botaoLinha.setText("Desenhar linha");
        botaoLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLinhaActionPerformed(evt);
            }
        });

        labelBotaoGrid.setText("Grid");

        botaoGrid.setText("Desligado");
        botaoGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGridActionPerformed(evt);
            }
        });

        labelCentro.setText("Centro");

        xCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCentroActionPerformed(evt);
            }
        });

        labelXCentro.setText("X");

        labelYCentro.setText("Y");

        yCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yCentroActionPerformed(evt);
            }
        });

        labelRaio.setText("Raio");

        raio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raioActionPerformed(evt);
            }
        });

        labelRaioR.setText("r");

        botaoCirculo.setText("Desenhar círculo");
        botaoCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCirculoActionPerformed(evt);
            }
        });

        jLabel1.setText("   0    1    2    3    4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelXInicialLinha)
                                            .addComponent(labelXFinalLinha, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(labelXCentro))
                                    .addComponent(labelRaioR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPontoInicialLinha)
                                    .addComponent(labelPontoFinalLinha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(xFinalLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                            .addComponent(xInicialLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelYInicialLinha)
                                            .addComponent(labelYFinalLinha))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(yInicialLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                            .addComponent(yFinalLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))
                                    .addComponent(botaoLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCentro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelYCentro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelRaio)
                                    .addComponent(raio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelBotaoGrid)
                            .addComponent(botaoGrid)))
                    .addComponent(jLabel1))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelPontoInicialLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXInicialLinha)
                            .addComponent(labelYInicialLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPontoFinalLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXFinalLinha)
                            .addComponent(labelYFinalLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoLinha)
                        .addGap(18, 18, 18)
                        .addComponent(labelCentro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXCentro)
                            .addComponent(labelYCentro)
                            .addComponent(yCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRaio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRaioR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                        .addComponent(labelBotaoGrid)
                        .addGap(2, 2, 2)
                        .addComponent(botaoGrid))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yInicialLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yInicialLinhaActionPerformed
        
    }//GEN-LAST:event_yInicialLinhaActionPerformed

    private void yFinalLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yFinalLinhaActionPerformed
        
    }//GEN-LAST:event_yFinalLinhaActionPerformed
    
    private void botaoLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLinhaActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        Bresenham bresenham = new Bresenham();
        int xInicial = 0, yInicial = 0, xFinal = 0, yFinal = 0;
        
        xInicial = Integer.parseInt(xInicialLinha.getText());
        yInicial = Integer.parseInt(yInicialLinha.getText());
        xFinal = Integer.parseInt(xFinalLinha.getText());
        yFinal = Integer.parseInt(yFinalLinha.getText());
        
        bresenham.iniciar_breserham(xInicial, xFinal, yInicial, yFinal, TAMPIXEL, qtde_pixels, g);
    }//GEN-LAST:event_botaoLinhaActionPerformed

    private void xInicialLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xInicialLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xInicialLinhaActionPerformed

    private void xFinalLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFinalLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xFinalLinhaActionPerformed

    private void botaoGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGridActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
  
        if(controle_grid == false){
            controle_grid = true;
            botaoGrid.setText("Ligado");
            for(int j=0; j<painelFrameBuffer.getHeight(); j=j+TAMPIXEL){
                for(int i=0; i<painelFrameBuffer.getWidth(); i=i+TAMPIXEL){
                    g.drawRect(i, j, TAMPIXEL, TAMPIXEL);
                }
            }   
        }else{
            controle_grid = false;
            botaoGrid.setText("Desligado");
            painelFrameBuffer.repaint();
        }
    }//GEN-LAST:event_botaoGridActionPerformed

    private void xCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xCentroActionPerformed

    private void yCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yCentroActionPerformed

    private void raioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raioActionPerformed

    private void botaoCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCirculoActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        PontoMedio pontoMedio = new PontoMedio();
        int xCentral = Integer.parseInt(xCentro.getText());
        int yCentral = Integer.parseInt(yCentro.getText());
        int raioCirculo = Integer.parseInt(raio.getText());
        
        pontoMedio.desenharCirculo(xCentral, yCentral, raioCirculo, TAMPIXEL, qtde_pixels, g);
    }//GEN-LAST:event_botaoCirculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCirculo;
    private javax.swing.JToggleButton botaoGrid;
    private javax.swing.JButton botaoLinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBotaoGrid;
    private javax.swing.JLabel labelCentro;
    private javax.swing.JLabel labelPontoFinalLinha;
    private javax.swing.JLabel labelPontoInicialLinha;
    private javax.swing.JLabel labelRaio;
    private javax.swing.JLabel labelRaioR;
    private javax.swing.JLabel labelXCentro;
    private javax.swing.JLabel labelXFinalLinha;
    private javax.swing.JLabel labelXInicialLinha;
    private javax.swing.JLabel labelYCentro;
    private javax.swing.JLabel labelYFinalLinha;
    private javax.swing.JLabel labelYInicialLinha;
    private javax.swing.JPanel painelFrameBuffer;
    private javax.swing.JTextField raio;
    private javax.swing.JTextField xCentro;
    private javax.swing.JTextField xFinalLinha;
    private javax.swing.JTextField xInicialLinha;
    private javax.swing.JTextField yCentro;
    private javax.swing.JTextField yFinalLinha;
    private javax.swing.JTextField yInicialLinha;
    // End of variables declaration//GEN-END:variables
  
public void construirGrade(){
    Graphics g = painelFrameBuffer.getGraphics();
    
    g.drawLine(0, 0, 200, 150);
}

}
