package projetocg;

import java.awt.Graphics;
import projetocg.Bresenham;

public class InterfacePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFrameBuffer = new javax.swing.JPanel();
        xInicialLinha = new javax.swing.JTextField();
        yInicialLinha = new javax.swing.JTextField();
        labelPontoInicialLinha = new javax.swing.JLabel();
        labelPontoFinalLinha = new javax.swing.JLabel();
        xFinalLinha = new javax.swing.JTextField();
        yFinalLinha = new javax.swing.JTextField();
        labelXInicialLinha = new javax.swing.JLabel();
        labelXFinalLinha = new javax.swing.JLabel();
        labelYInicialLinha = new javax.swing.JLabel();
        labelYFinalLinha = new javax.swing.JLabel();
        botaoLinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 680));

        painelFrameBuffer.setBackground(new java.awt.Color(255, 255, 255));
        painelFrameBuffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelFrameBuffer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelFrameBuffer.setMaximumSize(new java.awt.Dimension(642, 470));
        painelFrameBuffer.setMinimumSize(new java.awt.Dimension(642, 470));

        javax.swing.GroupLayout painelFrameBufferLayout = new javax.swing.GroupLayout(painelFrameBuffer);
        painelFrameBuffer.setLayout(painelFrameBufferLayout);
        painelFrameBufferLayout.setHorizontalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        painelFrameBufferLayout.setVerticalGroup(
            painelFrameBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        yInicialLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yInicialLinhaActionPerformed(evt);
            }
        });

        labelPontoInicialLinha.setText("Ponto inicial");

        labelPontoFinalLinha.setText("Ponto final");

        yFinalLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yFinalLinhaActionPerformed(evt);
            }
        });

        labelXInicialLinha.setText("X");

        labelXFinalLinha.setText("X");

        labelYInicialLinha.setText("Y");

        labelYFinalLinha.setText("Y");

        botaoLinha.setText("Desenhar linha");
        botaoLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelXInicialLinha)
                    .addComponent(labelXFinalLinha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPontoInicialLinha)
                    .addComponent(labelPontoFinalLinha)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xFinalLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(xInicialLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelYInicialLinha)
                            .addComponent(labelYFinalLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yInicialLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(yFinalLinha)))
                    .addComponent(botaoLinha))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelPontoInicialLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yInicialLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXInicialLinha)
                            .addComponent(labelYInicialLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPontoFinalLinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yFinalLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelXFinalLinha)
                            .addComponent(labelYFinalLinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoLinha))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelFrameBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yInicialLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yInicialLinhaActionPerformed
        
    }//GEN-LAST:event_yInicialLinhaActionPerformed

    private void yFinalLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yFinalLinhaActionPerformed
        
    }//GEN-LAST:event_yFinalLinhaActionPerformed

    private void botaoLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLinhaActionPerformed
        Graphics g = painelFrameBuffer.getGraphics();
        Bresenham bresenham = new Bresenham();
        int xInicial, yInicial, xFinal, yFinal;
        
        xInicial = Integer.parseInt(xInicialLinha.getText());
        yInicial = Integer.parseInt(yInicialLinha.getText());
        xFinal = Integer.parseInt(xFinalLinha.getText());
        yFinal = Integer.parseInt(yFinalLinha.getText());
        
        g.drawLine(xInicial, yInicial, xFinal, yFinal);
        //bresenham.desenharLinha(xInicial, yInicial, xFinal, yFinal);
    }//GEN-LAST:event_botaoLinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLinha;
    private javax.swing.JLabel labelPontoFinalLinha;
    private javax.swing.JLabel labelPontoInicialLinha;
    private javax.swing.JLabel labelXFinalLinha;
    private javax.swing.JLabel labelXInicialLinha;
    private javax.swing.JLabel labelYFinalLinha;
    private javax.swing.JLabel labelYInicialLinha;
    private javax.swing.JPanel painelFrameBuffer;
    private javax.swing.JTextField xFinalLinha;
    private javax.swing.JTextField xInicialLinha;
    private javax.swing.JTextField yFinalLinha;
    private javax.swing.JTextField yInicialLinha;
    // End of variables declaration//GEN-END:variables
}
